export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_REDUCE_ITEM = 'CART_REDUCE_ITEM';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';
export const CART_SET_CART_ITEMS= 'CART_SET_CART_ITEMS';



