export const USER_SET_SHIPPING_USER_INFO = 'USER_SET_SHIPPING_USER_INFO';
export const USER_SET_TYPE_PAY= 'USER_SET_TYPE_PAY';
export const USER_SET_USER_INFO = 'USER_SET_USER_INFO';
export const USER_SELECT_SHIPPING_VOUCHER = 'USER_SELECT_SHIPPING_VOUCHER';
export const USER_SELECT_INVOICE_VOUCHER = 'USER_SELECT_INVOICE_VOUCHER';
export const USER_PROCEED_CHECKOUT_REQUEST = 'USER_PROCEED_CHECKOUT_REQUEST'
export const USER_PROCEED_CHECKOUT_SUCCESS= 'USER_PROCEED_CHECKOUT_SUCCESS'
export const USER_PROCEED_CHECKOUT_FAIL= 'USER_PROCEED_CHECKOUT_FAIL'

