export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_ACCOUNT_REQUEST = 'USER_REGISTER_ACCOUNT_REQUEST';
export const USER_REGISTER_ACCOUNT_SUCCESS = 'USER_REGISTER_ACCOUNT_SUCCESS';
export const USER_REGISTER_ACCOUNT_FAIL= 'USER_REGISTER_ACCOUNT_FAIL';